## Basisc of Python Continue

In [1]:
a = 'is'
b = 'nice'

In [2]:
my_list = ['my', 'list', a, b]

In [3]:
my_list_02 = [[4, 5, 6, 7], [3, 4, 5, 6]]

In [4]:
my_list.append('!')

In [5]:
my_list

['my', 'list', 'is', 'nice', '!']

In [6]:
my_list.remove('!')

In [7]:
my_list

['my', 'list', 'is', 'nice']

In [8]:
del(my_list[0:1])

In [9]:
my_list

['list', 'is', 'nice']

In [10]:
my_list.reverse()

In [11]:
my_list

['nice', 'is', 'list']

In [12]:
my_list.extend('!')

In [13]:
my_list

['nice', 'is', 'list', '!']

In [14]:
my_list.pop(-1)

'!'

In [15]:
my_list

['nice', 'is', 'list']

In [16]:
my_list.insert(0, '!')

In [17]:
my_list

['!', 'nice', 'is', 'list']

In [18]:
my_list.sort()

In [19]:
my_list

['!', 'is', 'list', 'nice']

In [20]:
my_str = "thisStringIsAwesome"

In [21]:
my_str[3]

's'

In [22]:
my_str[4:9]

'Strin'

In [23]:
my_str.upper()

'THISSTRINGISAWESOME'

In [24]:
my_str.lower()

'thisstringisawesome'

In [25]:
my_str.count('w')

1

In [26]:
my_str.count('i')

2

In [27]:
my_str.replace('e', 'i')

'thisStringIsAwisomi'

In [28]:
my_str.strip()

'thisStringIsAwesome'

In [29]:
import numpy
import numpy as np

In [30]:
from math import pi

In [31]:
my_list = [1, 2, 3, 4]

In [32]:
my_arr = np.array(my_list)

In [33]:
my_2darr = np.array([[1, 2, 3], [4, 5, 6]])

In [34]:
my_arr[1]

2

In [35]:
my_arr[0:2]

array([1, 2])

In [36]:
my_2darr[:,0]

array([1, 4])

In [37]:
my_arr > 3

array([False, False, False,  True])

In [38]:
my_arr * 2

array([2, 4, 6, 8])

In [39]:
my_arr + np.array([5, 6, 7, 8])

array([ 6,  8, 10, 12])

In [40]:
my_arr.shape

(4,)

In [41]:
np.array(my_arr)

array([1, 2, 3, 4])

In [42]:
np.insert(my_arr, 1, 5)

array([1, 5, 2, 3, 4])

In [43]:
np.mean(my_arr)

2.5

In [44]:
np.median(my_arr)

2.5

In [45]:
np.corrcoef(my_arr)

1.0

In [46]:
np.std(my_arr)

1.118033988749895